name: gravitation
channels:
  - conda-forge
dependencies:
  - python=3.11
  - numpy
  - scipy
  - pandas
  - matplotlib
  - astropy
  - pip
  - pip:
      - classy==3.3.2.0
  - spectral-cube
  - pip
  - pip:
      - mkdocs
      - jinja2
      - pillow
