site_name: Gravitation SOTA
site_url: 
theme:
  name: material
nav:
  - Home: index.md
  - State of the Art: state-of-the-art.md
docs_dir: docs
site_dir: site
markdown_extensions:
  - toc
  - tables
  - admonition

